### ISSUE TITLE
Managing viralrecon execution

### ISSUE THREAD

**Issue by Shettland** [BU-ISCIII/relecov-tools#240]
Preparing the data to launch viralrecon and to extract the necessary data for read-bioinfo-metadata is a time-consuming process that has to be done manually right now. It could be rather easily automated with one or two modules.

**Comment by saramonzon** [comment]
duplicated #245?

**Comment by Shettland** [comment]
Not the same, this one aims to extract the necessary characteristics of the samples for the bioinformatics analysis like filenames, reference, paired-end or single-end, long or short-reads and generate a template to run viralrecon with the correspondent parameters (or IRMA if necessary) depending on key points. 
 On the other hand, #245  just mentions the necessity to process the log file created using --log to generate a summary report of the execution and maybe combine it with an automatic email to the submitter

**Comment by Shettland** [comment]
Ok you are refering to #244 . Its an extension of this one so yeah, I'll delete it.

**Comment by saramonzon** [comment]
yes, it was #244 sorry xD, add the extended description here so we don't loose it :)

**Comment by Shettland** [comment]
A new module could be implemented to do the following tasks:

1. Create folder structure to launch viralrecon/IRMA in the desired folder (HPC), taking support from buisciii-tools
2. Copy/move the fastq files to RAW
3. Extract metadata from json with .get("r1/r2_fastq_filepath") to create the samplesheet 
4. Extract necessary metadata for configuration files (paired/single-end, flu/RSV/SARS...)
5. Load the necessary modules
6. Launch viralrecon if possible

**Comment by Shettland** [comment]
This issue was adressed in https://github.com/BU-ISCIII/relecov-tools/pull/286
