### ISSUE TITLE
pipeline-manager batch folder name is taking time

### ISSUE THREAD

**Issue by svarona** [BU-ISCIII/relecov-tools#341]
When running pipeline-manager, the folder name that is being created in scratch is taking time for naming: `20241127_RLV_20240917 16:24:22_GROUP01_icasas_C`

When it should be `20241127_RLV_20240917_GROUP01_icasas_C`

Command used:
```
relecov-tools --log-file ./pipeline_manager.log pipeline-manager -i /data/bioinfoshare/UCCT_Relecov/ -t /data/bi/pipelines/buisciii-tools/bu_isciii/templates/viralrecon/ -o /data/bi/scratch_tmp/bi/ -l '20240917162422'
```

**Comment by Shettland** [comment]
Fixed #342
