### ISSUE TITLE
Check relecov schema for bioinfo fields

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/relecov-tools#49]

**Comment by ErikaKvalem** [comment]
https://docs.google.com/spreadsheets/d/19Xb0e7kPNtZkcYa3lKeYMHN5CcUgfkPQ1lHwm0y5elU/edit

**Comment by ErikaKvalem** [comment]
- Tengo que cambiar las label Bioinformatics and QC metrics en el relecov schema de todos los campos de metadatos de bioinfo https://docs.google.com/spreadsheets/d/19Xb0e7kPNtZkcYa3lKeYMHN5CcUgfkPQ1lHwm0y5elU/edit#gid=0

**Comment by ErikaKvalem** [comment]
Ya están cambiadas las labels a  Bioinformatics and QC metrics en el relecov schema
