### ISSUE TITLE
Upload 96 samples

### ISSUE THREAD

**Issue by ErikaKvalem** [BU-ISCIII/relecov-tools#69]

**Comment by ErikaKvalem** [comment]
- Recibir excel relleno Maria 
- [ ] Subir fastq 
- [ ] Subir fasta 
- [ ] Metadatos de bioinfo a mano 
- [ ] VCF 
- [ ] Long table
- [ ] Tabla stats 
- [ ] readme con versiones de los programas usados

**Comment by ErikaKvalem** [comment]
- [ ] Revisar metadata

**Comment by luissian** [comment]
He borrado la carpeta que estaba vacia de ivar/consensun

**Comment by saramonzon** [comment]
Hay que correr ese servicio con DSL2 para copiar los consensos, vcf ,etc con los nuevos formatos para no tener que parsear dos cosas.

- [x] Recibir excel relleno Maria (podemos subirlo sin CTs) 
- [x] conectar con galeon
- [x] carpeta para el ISCII @Alema91 --> ___siglas___ --> carpeta con fecha de secuenciacion 
- [x] fastq
- [ ] Correr viralrecon dsl2 
- [ ] fasta 
- [ ] Metadatos de bioinfo a mano 
- [ ] VCF 
- [ ] Long table
- [ ] Tabla stats 
- [ ] readme con versiones de los programas usados

**Comment by ErikaKvalem** [comment]
- [ ] Hacer subida de prueba de las 96 fastq a dev ENA 
- [ ] Hacer subida definitiva de las 96 fastq a ENA

**Comment by ErikaKvalem** [comment]
En la carpeta UCCT_Relecov tengo que añadir: 
- [ ] Excel relleno Maria (podemos subirlo sin CTs)
- [ ] Resultados de cada muestra pangolin 
- [ ] generar md5 por muestra 
- [ ] Mover ficheros fuera de carpetas 
- [ ] Los ficheros excel tienen que tener fecha

**Comment by ErikaKvalem** [comment]
- [ ] Volver a lanzar viralrecon habiendo cambiado la version de pangolin (La url y la carpeta) y añadir al bashrc singularity

**Comment by ErikaKvalem** [comment]
- [ ] generar fichero md5 por muestra
- [ ] Tabla stats
- [ ] fichero software_version from bioinfo_pipeline folder

**Comment by ErikaKvalem** [comment]
Cambio la fecha 28/04 a 19/05
